server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hotel_db?createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - loggers
          - info
  endpoint:
    loggers:
      enabled: true
  security:
    enabled: false

spring-doc:
  packagesToScan: com.service.hotel
  api-docs:
    path: /hotel/v3/api-docs/

